#!/bin/bash
set -eux

make

VOLUME_OPTS=""
if [ -d mnt ]; then
    VOLUME_OPTS="-v $(readlink -f mnt):/export"
fi

exec docker run -it --rm \
    -p 80:80 \
    --link postgres:db \
    ${VOLUME_OPTS} \
    bcclaywell/galaxy:testing \
    $@
